pulse_interface_testing.run: pulse_interface_testing.cpp ../pulse_interface.cpp
	g++ pulse_interface_testing.cpp ../pulse_interface.cpp -o pulse_interface_testing.run -lpulse

clean:
	rm pulse_interface_testing.run