main: main.h main.cpp
	g++ main.cpp -o main.o -lGL -lglut -lGLU -lpulse-simple -lpulse

main2: main.h main2.cpp
	g++ main2.cpp -o main2.o -lGL -lglut -lGLU -lpulse-simple -lpulse

main3: main3.h main3.cpp
	g++ main3.cpp -o main3.o -lGL -lglut -lGLU -lpulse-simple -lpulse -lfftw3